#!/bin/bash

# Copyright 2013 Richard Ricciardelli
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REMOTES=$(git remote)
for i in $REMOTES;
do
  printf '\n'
  echo $(tput bold)"Branch => $1..."$(tput sgr0)
  echo $(tput bold)"Uploading changes to $i please wait..."$(tput sgr0)
  git push $i $1
done

